### PR TITLE
Exclude Django model pk by default

### PR DESCRIPTION
**Pull request by jcarbaugh**
@CorneliusIV could use your thoughts on this, debating whether this is the right approach or not

### CODE REVIEW

**Comment by marcosmoyano** [comment]
I'd leave control to the user and not assume what they need/don't need. 
Example: In several of my use cases I need the `pk` field. In others I don't. It feels more natural to exclude a field from the existing fields than adding it back :thinking:

**Comment by CorneliusIV** [comment]
@jcarbaugh This is similar to DRF right? I think in some cases they exclude 'ID` by default as well. 
It did feel odd the first time I came across this behavior but I understand the idea of wanting a user to explicitly include IDs. 

I'm torn as well but leaning towards this being the correct approach.

**Comment by marcosmoyano** [comment]
DRF doesn't exclude `id` by default. (Example using DRF 3.9.4 and Django 2.1.3) 
```
In [1]: from customer.models import Customer

In [2]: from rest_framework import serializers

In [3]: from rest_framework.utils import model_meta

In [4]: class CS(serializers.ModelSerializer):
   ...:     class Meta:
   ...:         model = Customer
   ...:         fields = '__all__'
   ...:

In [5]: info = model_meta.get_field_info(Customer)

In [6]: cs = CS()

In [7]: cs.get_field_names(cs._declared_fields, info)
Out[7]:
['id',
 'first_name',
 'last_name',
 'email',
 'live',
 'created',
 'last_updated', ...]
```

**Comment by jcarbaugh** [comment]
@marcosmoyano that’s a good enough argument for me! I’ll reconsider for a moment and likely close this PR. Thanks!

**Pull request closed without merging**
